services:
  - type: web
    name: cloud-imc-app
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: imc-db-postgres
          property: connectionString

databases:
  - name: imc-db-postgres
    plan: free # PostgreSQL est 100% gratuit sur Render !