services:
  # 1. Configuration de l'application Java Spring Boot
  - type: web
    name: cloud-imc-app
    runtime: java
    buildCommand: mvn -f CloudIMC/pom.xml clean package -DskipTests
    startCommand: java -jar CloudIMC/target/*.jar
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: imc-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: imc-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: imc-db
          property: password

# 2. Configuration de la base de données MySQL
databases:
  - name: imc-db
    databaseName: imc_db
    user: imc_user
    plan: free
