services:
  # Service 1 : La base de données MySQL
  db:
    image: mysql:8.0
    container_name: imc-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imc_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_status_data:/var/lib/mysql

volumes:
  mysql_status_data: